### ISSUE TITLE
maxchecker dependency isolation

### ISSUE THREAD

**Issue by tap** [Cycling74/max-mxj#58]
Currently `maxchecker` poses a problem for embedding Java.

Ideally the code used by `maxchecker` for Java would be a part of the mxj package. Perhaps `maxchecker` could be refactored to load a DLL (plug-in), if it is present, for this case.

**Comment by pslack** [comment]
I was informed that Live 10 / Max 8 will no longer have maxchecker this could probably be closed ? @tap

**Comment by tap** [comment]
Good call!
